# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '13-数据刷新' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 13-数据刷新
  pod 'MJExtension'

end
