# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '12-自定义不等高Cell' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 12-自定义不等高Cell
  pod 'MJExtension'

end
